# Base configs
#baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Icy Films Productions"
subtitle: ""
author: "Dylan McDonald"
header:
 title: "Icy Films Productions"
 subtitle: "by Dylan McDonald"
footer:
 name: "Hey there, my name is Dylan"
 bio: "BIO"
 github: ""
web_design: "Tait Hoyem"
#social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
#  instagram: "https://www.instagram.com/ram_patra"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
